function [ measurementName ] = prepareMeasurementName()

    measurementName = struct('Name', [],...
                             'Surname', [],...
                             'NameCode', [],...
                             'Place', [],...
                             'PlaceCode', [],...
                             'Hand', [],...
                             'HandCode', [],...
                             'State', [],...
                             'StateCode',[]);

end

